import { useState } from "react";
import API from "../../utils/axios";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

export default function AdminExport() {

  const [type, setType] = useState("orders");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  // ================= FETCH =================
  const fetchData = async () => {
    const res = await API.get(`/export/${type}`, {
      params: { from, to }
    });
    return res.data;
  };

  // ================= FORMAT =================
  const formatData = (type, data) => {

    switch (type) {

      case "orders":
        return {
          headers: ["Order ID", "User", "Total", "Discount", "Final", "Status", "Date"],
          rows: data.map(o => [
            o._id,
            o.user?.email || "N/A",
            `₹${o.totalPrice}`,
            `₹${o.discount || 0}`,
            `₹${o.finalPrice}`,
            o.status,
            new Date(o.createdAt).toLocaleDateString()
          ])
        };

      case "users":
        return {
          headers: ["Name", "Email", "Role", "Joined"],
          rows: data.map(u => [
            u.name,
            u.email,
            u.role,
            new Date(u.createdAt).toLocaleDateString()
          ])
        };

      case "products":
        return {
          headers: ["Name", "Price", "Stock", "Created"],
          rows: data.map(p => [
            p.name,
            `₹${p.price}`,
            p.countInStock,
            new Date(p.createdAt).toLocaleDateString()
          ])
        };

      default:
        return {
          headers: Object.keys(data[0]),
          rows: data.map(d => Object.values(d))
        };
    }
  };

  // ================= CSV =================
  const exportCSV = async () => {

    const data = await fetchData();

    if (!data || data.length === 0) {
      return alert("No data to export");
    }

    const { headers, rows } = formatData(type, data);

    const csv = [
      headers.join(","),
      ...rows.map(row => row.join(","))
    ].join("\n");

    const blob = new Blob([csv], { type: "text/csv" });

    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${type}.csv`;
    link.click();
  };

  // ================= PDF =================
  const exportPDF = async () => {

    const data = await fetchData();

    if (!data || data.length === 0) {
      return alert("No data to export");
    }

    const { headers, rows } = formatData(type, data);

    const { jsPDF } = await import("jspdf");
    const autoTable = (await import("jspdf-autotable")).default;

    const doc = new jsPDF();

    // ================= LOAD LOGO =================
  const img = new Image();
  img.src = "/DJKavod.jpeg";

  await new Promise((resolve) => {
    img.onload = resolve;
  });

  // ================= ADD LOGO =================
  doc.addImage(img, "PNG", 150, 5, 40, 15);

    // 🔥 HEADER
    doc.setFontSize(16);
    doc.text("DJKavod Admin Report", 14, 15);

    doc.setFontSize(10);
    doc.text(
      `${type.toUpperCase()} | ${from || "All"} → ${to || "Now"}`,
      14,
      22
    );

    // 🔥 TABLE
    autoTable(doc, {
      head: [headers],
      body: rows,
      startY: 30,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [37, 99, 235] }
    });

    // 🔥 FOOTER
    const pageCount = doc.internal.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);

      doc.text(`Page ${i} of ${pageCount}`, 180, 290);
      doc.text("Generated by DJKavod Admin", 14, 290);
    }

    doc.save(`${type}-report.pdf`);
  };

  // ================= EXCEL =================
  const exportExcel = async () => {

    const data = await fetchData();

    if (!data || data.length === 0) {
      return alert("No data to export");
    }

    const { headers, rows } = formatData(type, data);

    const worksheet = XLSX.utils.aoa_to_sheet([
      headers,
      ...rows
    ]);

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, type);

    const excelBuffer = XLSX.write(workbook, {
      bookType: "xlsx",
      type: "array"
    });

    const file = new Blob([excelBuffer], {
      type: "application/octet-stream"
    });

    saveAs(file, `${type}-report.xlsx`);
  };

  return (
    <div className="admin-card">

      <h2>📤 Export Data</h2>

      <select value={type} onChange={e => setType(e.target.value)}>
        <option value="orders">Orders</option>
        <option value="users">Users</option>
        <option value="products">Products</option>
        <option value="coupons">Coupons</option>
      </select>

      <div style={{ display: "flex", gap: "10px", marginTop: 10 }}>
        <input type="date" value={from} onChange={e => setFrom(e.target.value)} />
        <input type="date" value={to} onChange={e => setTo(e.target.value)} />
      </div>

      <div style={{ marginTop: 15, display: "flex", gap: "10px" }}>
        <button onClick={exportCSV}>CSV</button>
        <button onClick={exportPDF}>PDF</button>
        <button onClick={exportExcel}>Excel</button>
      </div>

    </div>
  );
}